dataset:
  type: video
  input_path: data/virat_aerial/09152008flight2tape3_1.mpg
  camera_id: virat_aerial_01
  fps_override: null
  frame_limit: 120
  start_frame: 0
  image_extensions:
    - .jpg
    - .jpeg
    - .png
    - .bmp

annotations:
  type: none
  input_path: null
